[package]
name = "ferron-observability-memory"
version = "0.1.0"
edition = "2021"
description = "Example Ferron observability sink that stores events in memory (ferron-observability-memory)."
license = "MIT OR Apache-2.0"

[dependencies]

ferron-core = { git = "https://github.com/ferronweb/ferron", branch = "3.x" }
ferron-observability = { git = "https://github.com/ferronweb/ferron", branch = "3.x", features = ["module"] }

[dev-dependencies]
rustc-hash = "2"
