[package]
name = "ferron-echo-server"
version = "0.1.0"
edition = "2021"
description = "Example Ferron custom TCP echo server module (ferron-echo-server)."
license = "MIT OR Apache-2.0"

[dependencies]
async-trait = "0.1"
tokio = { version = "1", features = ["rt", "net", "io-util", "macros"] }

ferron-core = { git = "https://github.com/ferronweb/ferron", branch = "3.x" }

[dev-dependencies]
rustc-hash = "2"
