[package]
name = "ferron-tls-selfsigned"
version = "0.1.0"
edition = "2021"
description = "Example Ferron TLS provider that generates self-signed certificates (ferron-tls-selfsigned)."
license = "MIT OR Apache-2.0"

[dependencies]
async-trait = "0.1"
rcgen = "0.14"
rustls = { version = "0.23", default-features = false, features = ["std", "tls12", "aws_lc_rs"] }
rustls-pki-types = "1"

ferron-core = { git = "https://github.com/ferronweb/ferron", branch = "3.x" }
ferron-tls = { git = "https://github.com/ferronweb/ferron", branch = "3.x" }

[dev-dependencies]
rustc-hash = "2"
