name: Rust

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: Swatinem/rust-cache@v2

      - name: Run Cargo tests
        run: cargo test --workspace --verbose

      - name: Build fixture
        run: cargo build -p ferron-example-fixture --verbose

  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Check linting
        run: cargo clippy --workspace --all-targets -- -D warnings
        # For fixture as well (excluded from workspace)
        # run: cargo clippy -p ferron-example-fixture -- -D warnings

  depcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install cargo-shear
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall --no-confirm cargo-shear --force
      - name: Check for unused dependencies
        run: cargo shear

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install cargo-audit
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall --no-confirm cargo-audit --force
      - name: Check for vulnerable dependencies
        run: cargo audit
